#!/usr/bin/env bash
usage()
{
  echo "Usage: $0 dir"
  echo "dir - Project directory"
  exit 1
}

if [ "$#" -ne 1 ] || ! [ -d "$1" ]; 
then
  usage
fi

proj=$1

declare -i res=0
declare -r classesFile=".maincls"
declare -r nologo="-nologo"
declare -r parallel="-parallel+"
declare -r errorlog="-errorlog:"
declare -r reportanalyzer="-reportanalyzer"

set +o noglob
cd "$proj"
echo "$proj"
echo
printf -v findCmd '%q ' find . -type f -name '*.cs'
readarray -t args < <(eval $findCmd)
if [ ${#args[@]} -ne 0 ]; then
  if [ -e "$classesFile" ];
  then
    readarray -t classes < <(cat "$classesFile")
    for class in "${classes[@]}";
    do
      csc "${args[@]}" "$nologo" \
        "$parallel" \
        "$errorlog""$proj"".$class.errors" \
        "$reportanalyzer" -main:"$class"
      res=("$?"+"$res")
    done
  else
    csc "${args[@]}" "$nologo" \
      "$parallel" \
      "$errorlog""$proj"".errors" \
      "$reportanalyzer" 
    res="$?"
  fi
fi
cd ..
set -o noglob
exit "$res"
