#!/usr/bin/env bash
usage()
{
  echo "Usage: $0 dir"
  echo "dir - Project directory"
  exit 1
}

if [ "$#" -ne 1 ] || ! [ -d "$1" ]; 
then
  usage
fi

declare -i res=0

proj=$1

set +o noglob
cd "$proj"
printf -v findCmd '%q ' find . -type f -name '*.cs'
readarray -t args < <(eval $findCmd)
if [ ${#args[@]} -ne 0 ]; then
  csc "${args[@]}"
  res="$?"
fi
cd ..
set -o noglob
exit "$res"
