#!/usr/bin/env bash

######################################################################
# @author      : Linus Fernandes (linusfernandes@gmail.com)
# @file        : buildall
# @created     : Sunday May 31, 2020 03:21:19 IST
# @copyright   : Copyright (c) Linus Fernandes
# @description : 
######################################################################

find . -mindepth 2 -name "*.exe" -type f \
  ! -path "**/.git/**" -delete
find . -maxdepth 1 -type d -name "[[:upper:]]*" | \
  parallel --joblog build.log -j 5 -I% --max-args 1 ./build %
exit $?
