#!/usr/bin/env bash
usage()
{
  echo "Usage: $0 dir"
  echo "dir - Project directory"
  exit 1
}

readBuildOptions()
{
  [ -e "$proj/$buildOptionsFile" ] && \
    { buildOptions=$(cat "$proj"/"$buildOptionsFile") || \
      echo "Unable to read $proj/$buildOptionsFile";}
}

if [ "$#" -ne 1 ] || ! [ -d "$1" ]; 
then
  usage
fi

proj=$1

declare -i res=0
declare -r assemblyFile=".assemble"
declare -r nologo="-nologo"
declare -r buildOptionsFile=".buildoptions"
buildOptions=""

readBuildOptions
set +o noglob
cd "$proj"
echo "$proj"
echo
printf -v findCmd '%q ' find . -type f -name '*.cs'
readarray -t args < <(eval $findCmd)
if [ ${#args[@]} -ne 0 ]; then
  if [ -e "$assemblyFile" ];
  then
    readarray -t assemblies < <(cat "$assemblyFile")
    for assembly in "${assemblies[@]}";
    do
      cmd='mcs \
        "$nologo" $buildOptions \
        $assembly \
        "${args[@]}"'
      eval "$cmd"
      res=("$?"+"$res")
    done
  else
    mcs \
     "$nologo" $buildOptions \
      "${args[@]}"
    res="$?"
  fi
fi
cd ..
set -o noglob
exit "$res"
