#!/bin/bash
usage()
{
  echo "Usage: $0 dir"
  echo "dir - Project directory"
  exit 1
}

if [ "$#" -ne 1 ] || ! [ -d "$1" ]; 
then
  usage
fi

declare -i res=0

proj=$1

set +o noglob
printf -v findCmd '%q ' find $1 -type f -name '*.cs'
readarray -t args < <(eval $findCmd)
if [ ${#args[@]} -ne 0 ]; then
  clang-format -i -assume-filename=.clang-format \
    -style=file -sort-includes \
    "${args[@]}"
  res="$?"
fi
set -o noglob
exit "$res"
